"""
Phase 20B -- Advancement, Outletting & Early-Offense Decay.

TRANSITION-CAPABLE POSSESSION -> DECIDE HOW TO ADVANCE -> OPTIONAL
OUTLET/ADVANCE -> EARLY ATTACK OPPORTUNITY -> OR RESET TO HALFCOURT.
Does NOT resolve shot make/miss (Phase 18) or pass completion (Phase
17B) itself -- this module only (a) generates the ONE genuinely new
objective opportunity transition geometry requires (`OUTLET_PASS`,
additive to Phase 16's existing `action_opportunity.py`), and (b)
decays transition advantage back toward `HALFCOURT_SET` using Phase
15's own, already-built `AdvantageModel.decay()` interface.

============================ ARCHITECTURE AUDIT ============================
Confirmed by direct inspection: Phase 16's `ActionType.TRANSITION_PUSH`
already exists and is already generated by
`action_opportunity.generate_opportunities` whenever
`state.phase == PossessionPhase.TRANSITION` -- NO new action type or
generator change was needed for the "push" outcome. `DRIVE`/`PULL_UP`/
`CATCH_AND_SHOOT` (early attack) are likewise already generated under
ordinary live-dribble/just-caught preconditions, which hold identically
whether or not the possession is in transition -- so "early attack"
needed NO new mechanism either. `RESET_PASS`/`SWING_PASS` already exist
for the "reset" outcome. **The only real gap**: no existing opportunity
represents "pass to a teammate who is structurally AHEAD of the ball"
(Phase 20A's own `AHEAD_OF_BALL` relational tag) -- `SWING_PASS`
(nearest teammate) and `KICKOUT` (interior-origin, advantage-gated) do
not capture this. `ActionType.OUTLET_PASS` was added (additively, to
`action_intent.py`) for exactly this one real gap, and both `CREATION_ACTIONS`
(now including `TRANSITION_PUSH`) and `PASS_ACTIONS` (now including
`OUTLET_PASS`) were extended additively -- Phase 16's EXISTING
`_score_action` function in `action_selection.py` was NOT modified at
all; it already applies `role_off_initiation`'s boost to every
`CREATION_ACTIONS` member and `pass_vs_shoot`'s boost to every
`PASS_ACTIONS` member, so extending those two frozensets was sufficient
to give `TRANSITION_PUSH`/`OUTLET_PASS` correct, evidence-consistent
role/tendency sensitivity with ZERO new scoring code.
"""
from dataclasses import dataclass
from typing import List, Optional

from action_intent import ActionType
from action_opportunity import ObjectiveOpportunity, StructuralContext, generate_opportunities
from possession_advantage import AdvantageModel
from possession_engine import PossessionEngine
from possession_state import PossessionPhase, PossessionState, SpatialZone
from transition_state import AHEAD_OF_BALL, FloorPlayer, TransitionState, relational_tag


def generate_transition_opportunities(state: PossessionState, context: StructuralContext,
                                       transition_state: Optional[TransitionState] = None,
                                       advantage: Optional[AdvantageModel] = None) -> List[ObjectiveOpportunity]:
    """Thin, additive wrapper over Phase 16's own
    `action_opportunity.generate_opportunities` (called unmodified,
    first) -- appends `OUTLET_PASS` opportunities ONLY when
    `transition_state` supplies a real, structurally eligible receiver
    (an `AHEAD_OF_BALL`-tagged OFFENSE-side teammate, per Phase 20A's
    own relational tag -- never invented here). If `transition_state`
    is `None` or has no such receiver, this returns EXACTLY what Phase
    16 alone would have returned -- no silent behavior change outside
    real transition geometry."""
    opportunities = list(generate_opportunities(state, context, advantage))
    if transition_state is None or state.ball_carrier is None:
        return opportunities

    idx = len(opportunities) + 1
    for p in transition_state.player_zones:
        if p.side != "OFFENSE" or p.player_id == state.ball_carrier:
            continue
        if relational_tag(p.zone, transition_state.ball_zone) == AHEAD_OF_BALL:
            opportunities.append(ObjectiveOpportunity(
                opportunity_id=f"{state.possession_id}:OUTLET_PASS:{idx}", action_type=ActionType.OUTLET_PASS,
                actor_player_id=state.ball_carrier, target_player_id=p.player_id, target_zone=p.zone,
                source="transition_ahead_of_ball",
            ))
            idx += 1
    return opportunities


# --------------------------- decay / HALFCOURT_SET ---------------------------

def decay_transition(engine: PossessionEngine, dt: float) -> bool:
    """STATE-BASED decay (Candidate B, chosen over a fixed timer) --
    reuses Phase 15's own, already-built `AdvantageModel.decay(dt)`
    interface exactly as-is; this module invents no new decay
    coefficient or curve of its own (the concrete decay MATH still
    belongs to whichever `AdvantageModel` implementation is active,
    same representation-agnostic posture Phase 15/17A/17B already
    established). Returns True once the possession has reached
    `HALFCOURT_SET` (represented as `PossessionPhase.HALFCOURT` --
    Phase 15's own existing enum value, no new terminal state was
    created). Never ends the possession, never changes `possession_id`/
    offense team/ball carrier, never resets the shot clock."""
    if engine.advantage is not None:
        engine.advantage = engine.advantage.decay(dt)

    fully_recovered = engine.advantage is None or len(engine.advantage.compromised_areas()) == 0
    if fully_recovered and engine.state.phase == PossessionPhase.TRANSITION:
        from dataclasses import replace
        engine.state = replace(engine.state, phase=PossessionPhase.HALFCOURT)
    return engine.state.phase != PossessionPhase.TRANSITION
